### ISSUE TITLE
Type error from using missing exported member

### ISSUE THREAD

**Issue by sacki5** [justintaddei/v-wave#163] opened 2021-09-07 11:58 UTC
Getting this type error. Using vue version `2.6.14`. Looks like vue does not have the typing used. 
```
ERROR in .../node_modules/v-wave/dist/types/index.d.ts(1,10)
Module '"vue"' has no exported member 'Plugin'.
    1 | import { Plugin } from 'vue';
      |          ^
    2 | declare const VWave: Plugin & {
    3 |     installed: boolean;
    4 | };
```

**Comment by justintaddei** [comment] 2021-09-07 15:09
Thank you. I'll check into this sometime this afternoon.

**Comment by justintaddei** [comment] 2021-09-13 23:45
Can you share your main.js (or where ever you are registering the plugin with `Vue.use`)? I'm having trouble reproducing this.
Also, please provide your `tsconfig` file.

Thank you!

**Comment by justintaddei** [comment] 2021-09-14 00:02
I've successfully tested using a new Vue 2 + typescript project generated with the Vue CLI. 
![image](https://user-images.githubusercontent.com/16705594/133172312-3a65fbc6-ca42-4dac-892a-30499c47a198.png)

**Comment by justintaddei** [comment] 2021-09-21 00:05
Closing this issue because I cannot reproduce it. If you can provide more information about the scenario in which this occurred, I will revisit it.

**Closed by justintaddei** 2021-09-21 00:05 UTC
